name: Test Github Action
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Compile basic LaTeX document
        uses: ./
        with:
          root_file: dissertation.tex
          working_directory: test/
