name: Test Github Action
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: sikos/thesis@master
        with:
          root_file: dissertation.tex
          working_directory: test/
