name: Test Github Action
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - uses: xu-cheng/latex-action@v2
        with:
          root_file: dissertation.tex
          latexmk_use_xelatex: true
